{{- if .Values.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-helloworld.configMapName" . }}
  labels:
    {{- include "helm-helloworld.labels" . | nindent 4 }}
{{- with .Values.configMap.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: special-config
# data:
#   SPECIAL_LEVEL: very
#   SPECIAL_TYPE: charm
